USE ERP;

-- CRIANDO PROCEDURE PARA INTEGRAR AS NOTAS FISCAIS COM O PROCESSO DO FINANCEIRO
CREATE PROCEDURE PROC_INTEGR_FIN (@COD_EMPRESA INT)
AS
	SET NOCOUNT ON
	DECLARE @TIP_NF CHAR(1),
			@NUM_NF INT,
			@ID_CLIFOR DECIMAL(10,2),
			@COD_PAGTO INT,
			@DATA_EMISSAO DATE,
			@VENCIMENTO DATE,
			@TOTAL_NF DECIMAL(10,2),
			@VALOR_PARC DECIMAL(10,2),
			@PARC INT,
			@CONT_PARC INT,
			@ERRO_INTERNO INT
	
	BEGIN
		BEGIN TRANSACTION
			BEGIN TRY
-- VERIFICANDO SE EXISTE NOTA FISCAL PARA INTEGRAR
			IF (SELECT COUNT(*) FROM NOTA_FISCAL
				WHERE COD_EMPRESA = @COD_EMPRESA
				AND INTEGRADA_FIN = 'N') = 0
					BEGIN
						SET @ERRO_INTERNO = 1;
					END
			ELSE
				BEGIN
					DECLARE CONTPARC CURSOR FOR
					SELECT A.NUM_NF, COUNT(*) CONT_PARC
					FROM NOTA_FISCAL A
						INNER JOIN COND_PAGTO_DET B
						ON A.COD_PAGTO = B.COD_PAGTO
					WHERE A.COD_EMPRESA = @COD_EMPRESA
					AND A.INTEGRADA_FIN = 'N'
					GROUP BY A.NUM_NF
					
					OPEN CONTPARC
						FETCH NEXT FROM CONTPARC
						INTO @NUM_NF, @CONT_PARC
						WHILE @@FETCH_STATUS = 0
							BEGIN
								DECLARE INTEGRA_FIN CURSOR FOR
								SELECT A.TIP_NF, A.NUM_NF, A.ID_CLIFOR, A.COD_PAGTO, A.DATA_EMISSAO,
								CAST(DATEADD(DD,B.DIAS, A.DATA_EMISSAO) AS DATE)VENCIMENTO, A.TOTAL_NF,
								CAST(A.TOTAL_NF / 100 * B.PCT AS DECIMAL(10,2)) VALOR_PARC, B.PARC
								FROM NOTA_FISCAL A
									INNER JOIN COND_PAGTO_DET B
									ON A.COD_PAGTO = B.COD_PAGTO
								WHERE COD_EMPRESA = @COD_EMPRESA
								AND A.INTEGRADA_FIN = 'N'
								AND NUM_NF = @NUM_NF
								
								OPEN INTEGRA_FIN
									FETCH NEXT FROM INTEGRA_FIN
									INTO @TIP_NF, @NUM_NF, @ID_CLIFOR, @COD_PAGTO,
									@DATA_EMISSAO, @VENCIMENTO, @TOTAL_NF, @VALOR_PARC, @PARC
									WHILE @@FETCH_STATUS = 0
										BEGIN
-- INTEGRANDO NOTAS FISCAIS DE SAÍDA
										IF @TIP_NF = 'S'
											BEGIN
												INSERT INTO CONTAS_RECEBER
												VALUES (@COD_EMPRESA, @ID_CLIFOR, @NUM_NF, @PARC,
														@VENCIMENTO, NULL, @VALOR_PARC);
												SELECT 'DOCUMENTO VENDAS', @NUM_NF , 'INTEGRADO COM SUCESSO ',
												'PARCELA ' , @PARC, 'VALOR ', @VALOR_PARC
											END
-- INTEGRANDO NOTAS FISCAIS DE ENTRADA
										ELSE IF @TIP_NF = 'E'
											BEGIN
												INSERT INTO CONTAS_PAGAR
												VALUES (@COD_EMPRESA, @ID_CLIFOR, @NUM_NF, @PARC,
														@VENCIMENTO, NULL, @VALOR_PARC);
												SELECT 'DOCUMENTO COMPRAS', @NUM_NF ,'INTEGRADO COM SUCESSO ',
												'PARCELA ' , @PARC, 'VALOR ', @VALOR_PARC
											END
-- ATUALIZANDO STATUS NAS NOTAS FISCAIS
										IF @CONT_PARC = @PARC
											BEGIN
												SELECT 'ATUALIZA ' + CAST(@NUM_NF AS VARCHAR(100))
												UPDATE NOTA_FISCAL SET INTEGRADA_FIN = 'S'
												WHERE COD_EMPRESA = @COD_EMPRESA
												AND NUM_NF = @NUM_NF;
											END
					
											FETCH NEXT FROM INTEGRA_FIN
											INTO @TIP_NF, @NUM_NF, @ID_CLIFOR, @COD_PAGTO,
											@DATA_EMISSAO, @VENCIMENTO, @TOTAL_NF, @VALOR_PARC, @PARC;
									END
								CLOSE INTEGRA_FIN
								DEALLOCATE INTEGRA_FIN

									FETCH NEXT FROM CONTPARC
									INTO @NUM_NF, @CONT_PARC

								END
							CLOSE CONTPARC
							DEALLOCATE CONTPARC
				END
			END TRY
		BEGIN CATCH
			SELECT
				ERROR_NUMBER() AS ERRORNUMBER,
				ERROR_SEVERITY() AS ERRORSEVERITY,
				ERROR_STATE() AS ERRORSTATE,
				ERROR_PROCEDURE() AS ERRORPROCEDURE,
				ERROR_LINE() AS ERRORLINE,
				ERROR_MESSAGE() AS ERRORMESSAGE;

					IF (SELECT CURSOR_STATUS('GLOBAL', 'INTEGRA_FIN')) = 1
						BEGIN
							CLOSE INTEGRA_FIN
							DEALLOCATE INTEGRA_FIN
						END
					IF (SELECT CURSOR_STATUS('GLOBAL', 'CONTPARC')) = 1
						BEGIN
							CLOSE CONTPARC
							DEALLOCATE CONTPARC
						END
		
				SET XACT_ABORT ON;
					IF @@TRANCOUNT > 0  
						ROLLBACK TRANSACTION; 
		END CATCH

-- VALIDAÇÕES FINAIS
			IF @@ERROR <> 0 
				BEGIN
					ROLLBACK TRANSACTION
					PRINT @@ERROR
					PRINT 'OPERAÇÃO CANCELADA' 
				END
			ELSE IF @ERRO_INTERNO = 1
				BEGIN 
					ROLLBACK TRANSACTION 
					PRINT 'NÃO EXISTEM DOCUMENTOS PARA SEREM PROCESSADOS'
				END
			ELSE
				BEGIN
					COMMIT TRANSACTION
					PRINT 'INTEGRAÇÃO CONCLUÍDA'
				END 
		END;

-- EXECUTANDO PROCEDURE PROC_INTEGR_FIN
EXECUTE PROC_INTEGR_FIN 1;