USE ERP;

-- CRIANDO PROCEDURE PARA GERAR NOTA FISCAL
-- AJUSTANDO O CAMPO QTD DA TABELA NOTA_FISCAL_ITENS PARA DECIMAL(10,2)
ALTER TABLE NOTA_FISCAL_ITENS ALTER COLUMN QTD DECIMAL(10,2);

CREATE PROCEDURE PROC_GERA_NF (@COD_EMPRESA INT,
                               @TIP_MOV CHAR(1),
                               @DOCTO INT,
							   @CFOP VARCHAR(5),
							   @DATA_EMIS DATE,
							   @DATA_ENTREGA DATE)
AS 
	BEGIN 
		DECLARE @NOTA_TB TABLE (NF INT)
				@DOCT INT,
				@NUM_NF INT,
				@ID INT,
				@COD_PAGTO INT,
				@NUM_PEDIDO INT,
				@SEQ_MAT INT,
				@COD_MAT INT,
				@QTD DECIMAL(10,2),
				@VAL_UNIT DECIMAL (10,2),
				@SUB_TOT_NFE DECIMAL(10,2),
				@TOTAL_NFE DECIMAL(10,2),
				@ERRO_INTERNO INT

				SET @SUB_TOT_NFE = 0
				SET @TOTAL_NFE = 0

				BEGIN TRANSACTION
				BEGIN TRY
					IF (@DATA_EMIS > GETDATE() OR @DATA_ENTREGA > GETDATE())
						BEGIN
							PRINT 'NÃO PERMITIDO LANÇAMENTOS FUTUROS'
							SET @ERRO_INTERNO = 1
						END
					ELSE IF @TIP_MOV <> 'S' AND @TIP_MOV <> 'E'
						BEGIN
							PRINT 'OPERAÇÃO NÃO PERMITIDA E CANCELADA'
							SET @ERRO_INTERNO = 1
						END
					ELSE IF @TIP_MOV = 'S' AND (SELECT COUNT(*) FROM PED_VENDAS A
						WHERE COD_EMPRESA = @COD_EMPRESA AND A.NUM_PEDIDO = @DOCTO
						AND A.SITUACAO <> 'F') = 0
							BEGIN
								PRINT 'NÃO EXISTE PEDIDO DE VENDAS DISPONÍVEL PARA SAÍDA'
								SET @ERRO_INTERNO = 1
							END
					ELSE IF @TIP_MOV = 'E' AND (SELECT COUNT(*) FROM PED_COMPRAS A
						WHERE COD_EMPRESA = @COD_EMPRESA AND A.NUM_PEDIDO = @DOCTO
						AND A.SITUACAO <> 'F') = 0
							BEGIN
								PRINT 'NÃO EXISTE PEDIDO DE COMPRAS DISPONÍVEL PARA ENTRADA'
								SET @ERRO_INTERNO = 1
							END
					ELSE IF @TIP_MOV = 'S'
						BEGIN
							DECLARE NOTA_FISCAL CURSOR FOR
								SELECT A.COD_EMPRESA, A.NUM_PEDIDO, A.ID_CLIENTE, A.COD_PAGTO
								FROM PED_VENDAS A
								WHERE A.COD_EMPRESA = @COD_EMPRESA
								AND A.NUM_PEDIDO = @DOCTO
								AND A.SITUACAO <> 'F'
							OPEN NOTA_FISCAL
								FETCH NEXT FROM NOTA_FISCAL
								INTO @COD_EMPRESA, @NUM_PEDIDO, @ID, @COD_PAGTO
								WHILE @@FETCH_STATUS = 0
									BEGIN
-- PEGANDO NÚMERO DO PEDIDO
										PRINT 'UPDATE DE PARÂMETROS'
										UPDATE PARAMETROS SET VALOR = VALOR + 1
										OUTPUT INSERTED.VALOR INTO @NOTA_TB
										WHERE COD_EMPRESA = @COD_EMPRESA
										AND PARAM = 'NOTA_FISCAL';
		
-- ATRIBUINDO NÚMERO NF A VARIÁVEL
										SELECT @NUM_NF=NF FROM @NOTA_TB
										INSERT INTO NOTA_FISCAL
										OUTPUT INSERTED.NUM_NF
										VALUES
										(@COD_EMPRESA, @NUM_NF, @TIP_MOV, @CFOP, @ID,
										 @COD_PAGTO, @DATA_EMIS, @DATA_ENTREGA ,0, 'N', 'N')
										PRINT @@ERROR
-- IMPRIMININDO CABEÇALHO
										SELECT @COD_EMPRESA COD_EMPRESA, @NUM_NF NUM_NF, @TIP_MOV TIP_MOV,
										@CFOP CFOP, @ID ID, @COD_PAGTO COD_PAGTO,@DATA_EMIS DAT_EMIS,
										@DATA_ENTREGA DATA_ENTREG

										DECLARE NF_ITENS CURSOR FOR
											SELECT A.COD_EMPRESA, A.SEQ_MAT, A.COD_MAT, A.QTD, A.VAL_UNIT
											FROM PED_VENDAS_ITENS A
											WHERE COD_EMPRESA = @COD_EMPRESA
											AND A.NUM_PEDIDO = @DOCTO
											ORDER BY A.SEQ_MAT
										OPEN NF_ITENS
											FETCH NEXT FROM NF_ITENS
											INTO @COD_EMPRESA, @SEQ_MAT, @COD_MAT, @QTD, @VAL_UNIT
											WHILE @@FETCH_STATUS = 0
												BEGIN
													INSERT INTO NOTA_FISCAL_ITENS VALUES
													(@COD_EMPRESA, @NUM_NF, @SEQ_MAT,
													 @COD_MAT, @QTD, @VAL_UNIT, @DOCTO);
													PRINT @@ERROR
-- APRESENTANDO VALORES
													SELECT @COD_EMPRESA COD_EMPRESA, @NUM_NF NUM_NF,
													@SEQ_MAT SEQ , @COD_MAT COD_MAT, @QTD QTD,
													@VAL_UNIT VAL_UNIT, @DOCTO PED_ORIG
-- ATRIBUINDO VALORES
													SET @SUB_TOT_NFE = @QTD * @VAL_UNIT;
													SET @TOTAL_NFE = @TOTAL_NFE + @SUB_TOT_NFE;
													FETCH NEXT FROM NF_ITENS
													INTO @COD_EMPRESA, @SEQ_MAT, @COD_MAT, @QTD, @VAL_UNIT
													END
	  
										CLOSE NF_ITENS;
										DEALLOCATE NF_ITENS;
-- ATUALIZANDO TOTAL NFE
											UPDATE NOTA_FISCAL SET TOTAL_NF = @TOTAL_NFE
											WHERE COD_EMPRESA = @COD_EMPRESA AND NUM_NF = @NUM_NF;
-- ATUALIZANDO STATUS PARA FECHADO NFE
											UPDATE PED_VENDAS SET SITUACAO = 'F'
											WHERE COD_EMPRESA = @COD_EMPRESA AND NUM_PEDIDO = @DOCTO;

											FETCH NEXT FROM NOTA_FISCAL
											INTO @COD_EMPRESA, @NUM_PEDIDO, @ID, @COD_PAGTO
											END
										CLOSE NOTA_FISCAL;
										DEALLOCATE NOTA_FISCAL;
									END
					ELSE IF @TIP_MOV = 'E'
						BEGIN
							DECLARE NOTA_FISCAL CURSOR FOR
								SELECT @COD_EMPRESA, A.NUM_PEDIDO, A.ID_FOR, A.COD_PAGTO
								FROM PED_COMPRAS A
								WHERE COD_EMPRESA = @COD_EMPRESA
								AND A.NUM_PEDIDO = @DOCTO
								AND A.SITUACAO <> 'F'

							OPEN NOTA_FISCAL
								FETCH NEXT FROM NOTA_FISCAL
								INTO @COD_EMPRESA, @NUM_PEDIDO, @ID, @COD_PAGTO
								WHILE @@FETCH_STATUS = 0
									BEGIN
-- PEGANDO NÚMERO DO PEDIDO
										PRINT 'UPDATE DE PARÂMETROS'
										UPDATE PARAMETROS SET VALOR = VALOR + 1
										OUTPUT INSERTED.VALOR INTO @NOTA_TB
										WHERE COD_EMPRESA = @COD_EMPRESA
										AND PARAM = 'NOTA_FISCAL';
-- ATRIBUINDO NÚMERO NF A VARIÁVEL
										SELECT @NUM_NF = NF FROM @NOTA_TB
-- INSERINDO REGISTO
										INSERT INTO NOTA_FISCAL
										VALUES
										(@COD_EMPRESA, @NUM_NF, @TIP_MOV, @CFOP, @ID, @COD_PAGTO,
										 @DATA_EMIS, @DATA_ENTREGA, 0, 'N', 'N')
										PRINT @@ERROR
-- IMPRIMINDO CABEÇALHO
										SELECT @COD_EMPRESA COD_EMPRESA, @NUM_NF NUM_NF, @TIP_MOV TIP_MOV,
										@CFOP CFOP, @ID ID, @COD_PAGTO COD_PAGTO, @DATA_EMIS DAT_EMIS,
										@DATA_ENTREGA DATA_ENTREG

									DECLARE NF_ITENS CURSOR FOR
										SELECT @COD_EMPRESA COD_EMPRESA, A.SEQ_MAT, A.COD_MAT, A.QTD, A.VAL_UNIT
										FROM PED_COMPRAS_ITENS A
										WHERE COD_EMPRESA = @COD_EMPRESA
										AND A.NUM_PEDIDO = @DOCTO
										ORDER BY A.SEQ_MAT
									OPEN NF_ITENS
										FETCH NEXT FROM NF_ITENS
										INTO @COD_EMPRESA, @SEQ_MAT, @COD_MAT, @QTD, @VAL_UNIT
										WHILE @@FETCH_STATUS = 0
											BEGIN
												INSERT INTO NOTA_FISCAL_ITENS VALUES
												(@COD_EMPRESA, @NUM_NF, @SEQ_MAT, @COD_MAT, @QTD, @VAL_UNIT, @DOCTO);
												PRINT @@ERROR
-- APRESENTANDO VALORES DOS ITENS INSERIDOS
												SELECT @COD_EMPRESA COD_EMPRESA, @NUM_NF NUM_NF, @SEQ_MAT SEQ,
												@COD_MAT COD_MAT, @QTD QTD, @VAL_UNIT VAL_UNIT, @DOCTO PED_ORIG
												SET @SUB_TOT_NFE = @QTD * @VAL_UNIT;
												SET @TOTAL_NFE = @TOTAL_NFE + @SUB_TOT_NFE;
										FETCH NEXT FROM NF_ITENS
										INTO @COD_EMPRESA, @SEQ_MAT, @COD_MAT, @QTD, @VAL_UNIT
										END
										CLOSE NF_ITENS;
										DEALLOCATE NF_ITENS;
-- ATUALIZANDO TOTAL NFE
									UPDATE NOTA_FISCAL SET TOTAL_NF = @TOTAL_NFE
									WHERE COD_EMPRESA = @COD_EMPRESA AND NUM_NF = @NUM_NF;
-- ATUALIZADO STATUS NFE
									UPDATE PED_COMPRAS SET SITUACAO = 'F'
									WHERE COD_EMPRESA = @COD_EMPRESA AND NUM_PEDIDO = @DOCTO;

								FETCH NEXT FROM NOTA_FISCAL
								INTO @COD_EMPRESA, @NUM_PEDIDO, @ID, @COD_PAGTO
								END
							CLOSE NOTA_FISCAL;
							DEALLOCATE NOTA_FISCAL;
							END
-- VALIDAÇÕES FINAIS
								IF @@ERROR <> 0
									BEGIN
										ROLLBACK TRANSACTION
										PRINT 'OPERAÇÃO CANCELADA'
									END
								ELSE IF @ERRO_INTERNO = 1
									BEGIN
										ROLLBACK TRANSACTION
										PRINT 'OPERAÇÃO CANCELADA COM SUCESSO'
									END
								ELSE
									BEGIN
										PRINT 'OPERAÇÃO FINALIZADA COM SUCESSO'
										COMMIT TRANSACTION
									END
							END TRY
								BEGIN CATCH
									SELECT ERROR_NUMBER() AS ERRORNUMBER,
										   ERROR_SEVERITY() AS ERRORSEVERITY,
										   ERROR_STATE() AS ERRORSTATE,
										   ERROR_PROCEDURE() AS ERRORPROCEDURE,
										   ERROR_LINE() AS ERRORLINE,
										   ERROR_MESSAGE() AS ERRORMESSAGE;

										IF (SELECT CURSOR_STATUS('GLOBAL', 'NOTA_FISCAL')) = 1
											BEGIN
												CLOSE NOTA_FISCAL
												DEALLOCATE NOTA_FISCAL
											END
										IF (SELECT CURSOR_STATUS('GLOBAL', 'NF_ITENS')) = 1
											BEGIN
												CLOSE NF_ITENS
												DEALLOCATE NF_ITENS
											END
											SET XACT_ABORT ON;
											IF @@TRANCOUNT > 0
											ROLLBACK TRANSACTION;
									END CATCH
								END;

-- EXECUTANDO PROCEDURE PROC_GERA_NF
EXEC PROC_GERA_NF 1, 'X', 1, '1.101', '2020-01-30', '2020-01-30';

EXEC PROC_GERA_NF 1, 'E', 1, '1.101', '2020-01-30', '2020-01-30';

EXEC PROC_GERA_NF 1, 'E', 2, '1.101', '2020-01-30', '2020-01-30';

EXEC PROC_GERA_NF 1, 'E', 3, '1.101', '2020-01-30', '2020-01-30';

EXEC PROC_GERA_NF 1, 'E', 4, '1.101', '2020-01-30', '2020-01-30';

EXEC PROC_GERA_NF 1, 'S', 1, '5.101', '2020-01-30', '2020-01-30';

EXEC PROC_GERA_NF 1, 'S', 2, '5.101', '2020-02-28', '2020-02-28';

EXEC PROC_GERA_NF 1, 'S', 3, '5.101', '2020-03-30', '2020-03-30';

EXEC PROC_GERA_NF 1, 'S', 4, '5.101', '2020-04-30', '2020-04-30';

-- LISTANDO DIFERENÇAS SE OCORREREM
SELECT A.COD_EMPRESA, A.NUM_NF,A.TOTAL_NF, SUM(B.QTD*B.VAL_UNIT) TOT_ITENS
FROM NOTA_FISCAL A
	INNER JOIN NOTA_FISCAL_ITENS B
	ON A.COD_EMPRESA = B.COD_EMPRESA
	AND A.NUM_NF = B.NUM_NF
GROUP BY A.COD_EMPRESA, A.NUM_NF, A.TOTAL_NF
HAVING A.TOTAL_NF <> SUM(B.QTD * B.VAL_UNIT)