USE ERP;

-- CRIANDO TRIGGER PARA BLOQUEAR USUÁRIO QUANDO DEMITIDO
CREATE TRIGGER TG_BLOQUEIA_USUARIO ON FUNCIONARIO AFTER UPDATE
AS
	BEGIN
		DECLARE @COD_EMPRESA INT
		DECLARE @MATRICULA INT
		DECLARE @DATE_DEMISS DATE
		
		SELECT @COD_EMPRESA = I.COD_EMPRESA,
		@MATRICULA = I.MATRICULA,
		@DATE_DEMISS = I.DATE_DEMISS
		FROM INSERTED I;
		
		IF UPDATE(DATE_DEMISS) AND @DATE_DEMISS <> '1900-01-01'
			BEGIN
				UPDATE USUARIOS SET SITUACAO = 'B' -- BLOQUEIA
				WHERE COD_EMPRESA = @COD_EMPRESA
				AND MATRICULA = @MATRICULA;
				PRINT 'BLOQUEIO DA MATRÍCULA ' + CAST (@MATRICULA AS VARCHAR(20)) + ' REALIZADO COM SUCESSO';
			END
	END;

-- EXECUTANDO TRIGGER TG_BLOQUEIA_USUARIO
UPDATE FUNCIONARIO SET DATE_DEMISS = GETDATE()
WHERE COD_EMPRESA = 1
AND MATRICULA = '4';