-- CRIANDO DATABASE
CREATE DATABASE ERP
ON (NAME = ERP_DAT, FILENAME = 'C:\TEMP\DATA\ERP.MDF', SIZE = 50MB, MAXSIZE = 800MB, FILEGROWTH = 50MB)  
LOG ON (NAME = ERP_LOG, FILENAME = 'C:\TEMP\DATA\ERP.LDF', SIZE = 20MB, MAXSIZE = 400MB, FILEGROWTH = 20MB)
GO
USE ERP;