USE ERP;

-- CRIANDO PROCEDURE PARA GERAR ORDENS DE PRODUÇÃO COM BASE EM PEDIDOS DE VENDAS
CREATE PROCEDURE PROC_PLAN_ORDEM (@COD_EMPRESA INT, @MES VARCHAR(2), @ANO  VARCHAR(4)) AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ERRO_INTERNO INT;

-- VERIFICANDO SE EXISTE PEDIDO EM ABERTO PARA MÊS E ANO SELECIONANDO EMPRESA
BEGIN TRANSACTION
	SELECT A.COD_EMPRESA, A.NUM_PEDIDO
	FROM PED_VENDAS A
	WHERE A.COD_EMPRESA = @COD_EMPRESA
	AND A.SITUACAO = 'A'
	AND MONTH(A.DATA_ENTREGA) = @MES
	AND YEAR(A.DATA_ENTREGA) = @ANO
		IF @@ROWCOUNT = 0
	BEGIN
		SET @ERRO_INTERNO = 1;
	END
		ELSE
	BEGIN
		INSERT INTO ORDEM_PROD
		OUTPUT 'ORDEM PLANEJADA' MSG,INSERTED.COD_EMPRESA, INSERTED.ID_ORDEM, INSERTED.COD_MAT_PROD
		SELECT A.COD_EMPRESA, B.COD_MAT, SUM(B.QTD) AS QTD_PLAN, 0 QTD_PROD,
		@ANO + '-' + @MES + '-01' AS DATA_INI,
		EOMONTH(@ANO + '-' + @MES + '-01') AS DATA_FIM, 'A' -- EOMONTH RETORNA ÚLTIMO DIA DO MÊS DA DATA PARAM
		FROM PED_VENDAS A
		INNER JOIN PED_VENDAS_ITENS B
		ON A.NUM_PEDIDO = B.NUM_PEDIDO
		AND A.COD_EMPRESA = B.COD_EMPRESA
		WHERE A.COD_EMPRESA = @COD_EMPRESA
		AND A.SITUACAO = 'A' -- SOMENTE PEDIDOS EM ABERTO
		AND MONTH(A.DATA_ENTREGA) = @MES
		AND YEAR(A.DATA_ENTREGA) = @ANO
		GROUP BY A.COD_EMPRESA, B.COD_MAT;
		PRINT 'INSERT ORDEM PROD REALIZADA';
				UPDATE PED_VENDAS SET SITUACAO = 'P' -- ATUALIZANDO STATUS PEDIDO
				OUTPUT 'PEDIDO PLANEJADO' MSG ,INSERTED.NUM_PEDIDO, DELETED.SITUACAO DE, INSERTED.SITUACAO PARA
				WHERE COD_EMPRESA = @COD_EMPRESA
				AND SITUACAO = 'A'
				AND MONTH(DATA_ENTREGA) = @MES
				AND YEAR(DATA_ENTREGA) = @ANO;
				PRINT 'PEDIDOS SITUAÇÃO ATUALIZADA';
	END
 -- VERIFICANDO TESTES FINAIS
		IF @ERRO_INTERNO = 1
	BEGIN
		ROLLBACK
		RAISERROR ('NÃO EXISTEM MATERIAIS PARA PLANEJ. ORDEM', 10, 1); -- 10-SEVERITY, 1-STATE
		PRINT 'OPERAÇÃO CANCELADA ROLLBACK';
	END
		ELSE IF @@ERROR <> 0
	BEGIN
		ROLLBACK
		PRINT 'OPERAÇÃO CANCELADA'
		PRINT @@ERROR
	END
		ELSE
	BEGIN
		COMMIT
		PRINT 'OPERAÇÃO REALIZADA COM SUCESSO';
	END
END;

-- EXECUTANDO PROCEDURE PROC_PLAN_ORDEM
EXEC PROC_PLAN_ORDEM 1, 2, 2020;